name: colossaltech_docker

services:
  django_app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    container_name: colossaltech_postgres_container
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=colossaltech
      - POSTGRES_USER=mahesh
      - POSTGRES_PASSWORD=password
      - 

volumes:
  postgres_data: