version: "3.1"

services:

  db:
    restart: always
    image: postgres:9.6-alpine
    container_name: demo-postgres #you can change this
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_PORT=5432
      - POSTGRES_USER=mahesh
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST_AUTH_METHOD= "trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: demo-pgadmins
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always


volumes:
  postgres_data:
